# Site settings
username: Swetha Revanur
user_title: CS @ Stanford, Seeking January 2020 Roles
title: Swetha Revanur
subtitle1: by Swetha Revanur
subtitle2: Swetha Revanur
email: swetharevanur@gmail.com
description: A project portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swetharevanur.github.io" # the base hostname & protocol for your site


# Data Viz page tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/swetharevanur
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/swetharevanur
pinterest_url:
slack_url:
twitter_url: 
google_analytics: UA-104627130-1

# Build settings
markdown: kramdown
gems:
  - jekyll-archives
