# Site settings
title: dataviz
subtitle: by Swetha Revanur
email: srevanur@stanford.edu
description: A data visualization portfolio by Swetha Revanur.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://swetharevanur.github.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
github_url: https://github.com/swetharevanur
linkedin_url: https://www.linkedin.com/in/swetharevanur
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
