# Site settings
title: DATAVIZ
subtitle: by Swetha Revanur
email: srevanur@stanford.edu
description: A passion project portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swetharevanur.github.io" # the base hostname & protocol for your site
# author:
# street_address:
# city: 
# state: 
# zip_code: 
# country: 
# phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/swetharevanur
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/swetharevanur
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
gems:
  - jekyll-archives
