# Site settings
title: dataviz
subtitle: by Swetha Revanur
# email: youremailaddress@gmail.com
description: A passion project portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swetharevanur.github.io" # the base hostname & protocol for your site
# author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/swetharevanur
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/swetharevanur
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
